#!/usr/bin/env npx tsx
/**
 * Sync task.yaml files from runqy-tasks repo into src/lib/data/tasks.ts
 *
 * Usage: npx tsx scripts/sync-tasks.ts [path-to-runqy-tasks]
 * Default path: ../runqy-tasks
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { parse } from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const tasksRepoPath = resolve(process.argv[2] || join(__dirname, '..', '..', 'runqy-tasks'));

interface TaskYaml {
	name: string;
	display_name: string;
	category: string;
	tags: string[];
	hardware: string[];
	gpu_required: boolean;
	mode: string;
	avg_latency: string;
	memory_mb: number;
	description: string;
	long_description: string;
	models?: string[];
	tools?: string[];
	use_cases?: string[];
	input_example?: string;
	output_example?: string;
}

function findTaskYamls(dir: string): string[] {
	const results: string[] = [];
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		if (statSync(full).isDirectory()) {
			const taskFile = join(full, 'task.yaml');
			try {
				statSync(taskFile);
				results.push(taskFile);
			} catch {
				results.push(...findTaskYamls(full));
			}
		}
	}
	return results;
}

const yamlFiles = findTaskYamls(tasksRepoPath);
console.log(`Found ${yamlFiles.length} task.yaml files`);

const tasks: TaskYaml[] = yamlFiles.map((f) => {
	const raw = readFileSync(f, 'utf-8');
	return parse(raw) as TaskYaml;
});

// Sort: ai first, then media, then data; alphabetical within category
const order = { ai: 0, media: 1, data: 2 };
tasks.sort((a, b) => {
	const catDiff = (order[a.category as keyof typeof order] ?? 9) - (order[b.category as keyof typeof order] ?? 9);
	if (catDiff !== 0) return catDiff;
	return a.display_name.localeCompare(b.display_name);
});

const output = `// Auto-generated by scripts/sync-tasks.ts — do not edit manually
import type { Task } from '$lib/types/task';

export const tasks: Task[] = ${JSON.stringify(tasks, null, '\t')};
`;

const outPath = join(__dirname, '..', 'src', 'lib', 'data', 'tasks.ts');
writeFileSync(outPath, output);
console.log(`Wrote ${tasks.length} tasks to ${outPath}`);
